#ifndef CONFIG_H
#define CONFIG_H

#define WINDOW_TITLE "SquareWar"
#define WINDOW_WIDTH 1200
#define WINDOW_HEIGHT 800

#define TARGET_FPS 60
#define BACKGROUND_COLOR 0x00141414

#define DEAFULT_PLAYER_HEALTH 1000
#define DEAFULT_ENTITY_HEALTH 150
#define DEAFULT_PROJECTILE_DAMAGE 50
#define PLAYER_STEP 3

#endif